version: '{build}'
skip_tags: true
skip_commits:
  message: /\[ci skip\]/
clone_depth: 10
environment:
  nodejs_version: 0.12
install:
- git submodule update --init --recursive
- npm install
build_script:
- node npm/appveyor.js
- node npm/test/unsupported-features.js
- node npm/test/jasmine-bower.js
- node npm/test/jasmine-npm.js
- node npm/test/jasmine-webpack.js
- karma start
